"""Generate docs/findings.md from the live CSV pack.

Run:  python -m src.build_findings

Keeps the written findings report honest and reproducible: every number comes
straight from the analysis layer over the bundled sample, so re-running after a
data swap regenerates the report. Not a substitute for the interactive dashboard —
it's the static, shareable summary the spec's "final research report" calls for.
"""

from __future__ import annotations

from pathlib import Path

from . import analysis as an, data_access as da

OUT = da.PROJECT_ROOT / "docs" / "findings.md"


def _table(df, cols, headers) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(str(row[c]) for c in cols) + " |")
    return "\n".join(lines)


def build() -> str:
    df = da.safe_conversations()
    s = an.global_summary(df)

    topics = an.topic_counts(df)
    cats = an.topic_counts(df, "topic_category")
    langs = an.language_distribution(df)
    curiosity = an.curiosity_index(df, n=10)
    per_country = an.top_topics_per_country(df, n=3)

    parts = []
    parts.append("# Trendy Topic — Findings\n")
    parts.append(
        "> Auto-generated by `python -m src.build_findings` from the safe WildChat "
        "sample pack in `data/wildchat_country_csv_pack/`. These are **sample-scale** "
        "results for a starter dataset, not the full 3.2M-conversation WildChat corpus.\n"
    )

    parts.append("## Research question\n")
    parts.append(
        "What are the top things people around the world ask AI about, and how do "
        "those topics differ by country and language?\n"
    )

    parts.append("## Dataset at a glance\n")
    parts.append(
        f"- **{s['conversations']}** safe conversations across **{s['countries']}** "
        f"countries and **{s['languages']}** languages\n"
        f"- **{s['topics']}** topic labels; average **{s['avg_turns']}** turns per conversation\n"
        f"- **{s['redacted_pct']}%** of rows carried redacted PII (already stripped in this pack)\n"
        f"- 0 toxic rows (the pack is a curated safe preview)\n"
    )

    parts.append("## Top topics globally\n")
    parts.append(_table(topics, ["topic_label", "conversations"], ["Topic", "Conversations"]) + "\n")

    parts.append("## Broad topic categories\n")
    parts.append(_table(cats, ["topic_category", "conversations"], ["Category", "Conversations"]) + "\n")

    parts.append("## Language distribution\n")
    parts.append(_table(langs, ["language", "conversations", "share_pct"],
                        ["Language", "Conversations", "Share %"]) + "\n")

    parts.append("## Global Curiosity Index — most-asked questions\n")
    parts.append(_table(curiosity, ["rank", "conversations", "topic_label", "sample_user_prompt_cleaned"],
                        ["Rank", "Count", "Topic", "Question"]) + "\n")

    parts.append("## Top 3 topics per country\n")
    parts.append(_table(per_country, ["country", "topic_label", "conversations"],
                        ["Country", "Topic", "Conversations"]) + "\n")

    parts.append("## How to read this\n")
    parts.append(
        "Because the sample pack holds an equal 60 conversations per country, "
        "cross-country *volume* is flat by design — the meaningful signal is the "
        "**topic mix within each country** and the **shared global curiosity** "
        "questions. Load the full Hugging Face export (see `README.md` and "
        "`data/wildchat_country_csv_pack/export_actual_wildchat_by_country.py`) to "
        "surface real volume differences.\n"
    )

    parts.append("## Ethics & limits\n")
    parts.append(
        "All analysis runs on safe, PII-redacted summaries; toxic rows are excluded "
        "and raw chat text is never sent to translation or voice APIs. See "
        "`docs/ethics_policy.md`.\n"
    )

    return "\n".join(parts)


def main() -> None:
    OUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(da.PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
