"""Complete Dewey Decimal Classification taxonomy with detailed hierarchies.

This module provides a comprehensive reference for the Dewey Decimal Classification
system, organized with main classes, divisions, and sections. Used by the library
search, admin panel, and Dewey prompt explorer.
"""

# Complete Dewey Decimal Classification structure
DEWEY_TAXONOMY = {
    "000": {
        "name": "Computer Science, Information & General Works",
        "divisions": {
            "000-009": "Computer science & general information works",
            "010-019": "Bibliography & library science",
            "020-029": "Library & information sciences",
            "030-039": "General encyclopedic works",
            "040-049": "General works",
            "050-059": "General serial publications",
            "060-069": "Organizations & management",
            "070-079": "News & journalism",
            "080-089": "Quotations",
            "090-099": "Manuscripts & rare books",
        },
    },
    "100": {
        "name": "Philosophy & Psychology",
        "divisions": {
            "100-109": "Philosophy & psychology",
            "110-119": "Metaphysics",
            "120-129": "Epistemology",
            "130-139": "Paranormal phenomena & pseudopsychology",
            "140-149": "Specific philosophical schools",
            "150-159": "Psychology",
            "160-169": "Philosophical logic",
            "170-179": "Ethics",
            "180-189": "Ancient, medieval & eastern philosophy",
            "190-199": "Modern western philosophy",
        },
    },
    "200": {
        "name": "Religion",
        "divisions": {
            "200-209": "Religion",
            "210-219": "Natural theology",
            "220-229": "Bible",
            "230-239": "Christianity & Christian theology",
            "240-249": "Christian practice & observance",
            "250-259": "Christian pastoral theology",
            "260-269": "Christian social theology",
            "270-279": "History of Christianity & Christian churches",
            "280-289": "Christian denominations & sects",
            "290-299": "Other & comparative religions",
        },
    },
    "300": {
        "name": "Social Sciences",
        "divisions": {
            "300-309": "Social sciences",
            "310-319": "Statistics",
            "320-329": "Political science",
            "330-339": "Economics",
            "340-349": "Law",
            "350-359": "Public administration & military science",
            "360-369": "Social problems & social services",
            "370-379": "Education",
            "380-389": "Commerce, communications & transportation",
            "390-399": "Customs, etiquette & folklore",
        },
    },
    "400": {
        "name": "Language",
        "divisions": {
            "400-409": "Language",
            "410-419": "Linguistics",
            "420-429": "English & Old English languages",
            "430-439": "Germanic languages (German, etc.)",
            "440-449": "Romance languages (French, Italian, etc.)",
            "450-459": "Italian, Romanian, Rhaeto-Romanic",
            "460-469": "Spanish & Portuguese languages",
            "470-479": "Latin & Italic languages",
            "480-489": "Classical & modern Greek languages",
            "490-499": "Other languages",
        },
    },
    "500": {
        "name": "Science & Mathematics",
        "divisions": {
            "500-509": "Natural sciences & mathematics",
            "510-519": "Mathematics",
            "520-529": "Astronomy & allied sciences",
            "530-539": "Physics",
            "540-549": "Chemistry",
            "550-559": "Earth sciences & geology",
            "560-569": "Paleontology & fossil animals",
            "570-579": "Biology",
            "580-589": "Plants (Botany)",
            "590-599": "Animals (Zoology)",
        },
    },
    "600": {
        "name": "Technology (Applied Sciences)",
        "divisions": {
            "600-609": "Technology & applied sciences",
            "610-619": "Medicine & health",
            "620-629": "Engineering",
            "630-639": "Agriculture",
            "640-649": "Home & family management",
            "650-659": "Management & auxiliary services",
            "660-669": "Chemical & related technologies",
            "670-679": "Manufacturing",
            "680-689": "Manufacture for specific uses",
            "690-699": "Building & construction",
        },
    },
    "700": {
        "name": "Arts & Recreation",
        "divisions": {
            "700-709": "Arts & recreation",
            "710-719": "Civic & landscape design",
            "720-729": "Architecture",
            "730-739": "Sculpture",
            "740-749": "Graphic arts & decorative arts",
            "750-759": "Painting",
            "760-769": "Graphic & related arts",
            "770-779": "Photography & digital media",
            "780-789": "Music",
            "790-799": "Sports, games & entertainment",
        },
    },
    "800": {
        "name": "Literature",
        "divisions": {
            "800-809": "Literature & rhetoric",
            "810-819": "American literature in English",
            "820-829": "English & Old English literatures",
            "830-839": "German & related literatures",
            "840-849": "French & related literatures",
            "850-859": "Italian, Romanian, Rhaeto-Romanic literatures",
            "860-869": "Spanish & Portuguese literatures",
            "870-879": "Latin & Italic literatures",
            "880-889": "Classical & modern Greek literatures",
            "890-899": "Other literatures",
        },
    },
    "900": {
        "name": "History & Geography",
        "divisions": {
            "900-909": "History & geography",
            "910-919": "Geography & travel",
            "920-929": "Biography",
            "930-939": "History of ancient world (to 500 CE)",
            "940-949": "History of Europe",
            "950-959": "History of Asia",
            "960-969": "History of Africa",
            "970-979": "History of North America",
            "980-989": "History of South America",
            "990-999": "History of other areas",
        },
    },
}

# Detailed breakdown of specific classes
DEWEY_DETAILED = {
    "000": {
        "name": "Computer Science, Information & General Works",
        "full_breakdown": {
            "000-009": {
                "title": "Computer science, knowledge, systems",
                "sections": {
                    "000": "Computer science, information, and general works",
                    "001": "Knowledge",
                    "002": "The book",
                    "003": "Systems",
                    "004": "Computer science",
                    "005": "Computer programming, programs, data",
                    "006": "Special computer methods",
                    "007": "Not assigned / reserved",
                    "008": "Not assigned / reserved",
                    "009": "Historical, geographic, persons treatment",
                },
            },
            "010-019": {
                "title": "Bibliography",
                "sections": {
                    "010": "Bibliography",
                    "011": "Bibliographies",
                    "012": "Bibliographies of individuals",
                    "013": "Bibliographies of anonymous and pseudonymous works",
                    "014": "Of works from specific places",
                    "015": "Of works from specific places",
                    "016": "Bibliographies of works on specific subjects",
                    "017": "General subject catalogs",
                    "018": "Catalogs arranged by author, date, etc.",
                    "019": "Dictionary catalogs",
                },
            },
            "020-029": {
                "title": "Library & information sciences",
                "sections": {
                    "020": "Library & information sciences",
                    "021": "Library relationships",
                    "022": "Administration of physical plant",
                    "023": "Personnel management",
                    "024": "Not assigned / reserved",
                    "025": "Library operations",
                    "026": "Libraries for specific subjects",
                    "027": "General libraries",
                    "028": "Reading and use of other information media",
                    "029": "Not assigned / reserved",
                },
            },
            "030-039": {
                "title": "General encyclopedic works",
                "sections": {
                    "030": "General encyclopedic works",
                    "031": "American encyclopedias in English",
                    "032": "English encyclopedias",
                    "033": "German encyclopedias",
                    "034": "French encyclopedias",
                    "035": "Italian, Romanian, related encyclopedias",
                    "036": "Spanish, Portuguese encyclopedias",
                    "037": "Slavic encyclopedias",
                    "038": "Scandinavian encyclopedias",
                    "039": "Encyclopedias in other languages",
                },
            },
            "040-049": {
                "title": "Unassigned general works",
                "sections": {
                    "040": "Not assigned / reserved",
                    "041": "Not assigned / reserved",
                    "042": "Not assigned / reserved",
                    "043": "Not assigned / reserved",
                    "044": "Not assigned / reserved",
                    "045": "Not assigned / reserved",
                    "046": "Not assigned / reserved",
                    "047": "Not assigned / reserved",
                    "048": "Not assigned / reserved",
                    "049": "Not assigned / reserved",
                },
            },
            "050-059": {
                "title": "General serial publications",
                "sections": {
                    "050": "General serial publications",
                    "051": "American serials in English",
                    "052": "English serials",
                    "053": "German serials",
                    "054": "French serials",
                    "055": "Italian, Romanian, related serials",
                    "056": "Spanish, Portuguese serials",
                    "057": "Slavic serials",
                    "058": "Scandinavian serials",
                    "059": "Serials in other languages",
                },
            },
            "060-069": {
                "title": "Organizations & museum science",
                "sections": {
                    "060": "General organizations and museum science",
                    "061": "Organizations in North America",
                    "062": "Organizations in British Isles",
                    "063": "Organizations in Central Europe",
                    "064": "Organizations in France and Monaco",
                    "065": "Organizations in Italy and adjacent territories",
                    "066": "Organizations in Iberian Peninsula and adjacent islands",
                    "067": "Organizations in Eastern Europe",
                    "068": "Organizations in other geographic areas",
                    "069": "Museum science",
                },
            },
            "070-079": {
                "title": "News media, journalism, publishing",
                "sections": {
                    "070": "News media, journalism, publishing",
                    "071": "Newspapers in North America",
                    "072": "Newspapers in British Isles",
                    "073": "Newspapers in Central Europe",
                    "074": "Newspapers in France and Monaco",
                    "075": "Newspapers in Italy and adjacent territories",
                    "076": "Newspapers in Iberian Peninsula and adjacent islands",
                    "077": "Newspapers in Eastern Europe",
                    "078": "Newspapers in Scandinavia",
                    "079": "Newspapers in other geographic areas",
                },
            },
            "080-089": {
                "title": "General collections",
                "sections": {
                    "080": "General collections",
                    "081": "Collections in American English",
                    "082": "Collections in English",
                    "083": "Collections in German",
                    "084": "Collections in French",
                    "085": "Collections in Italian, Romanian, related",
                    "086": "Collections in Spanish, Portuguese",
                    "087": "Collections in Slavic languages",
                    "088": "Collections in Scandinavian languages",
                    "089": "Collections in other languages",
                },
            },
            "090-099": {
                "title": "Manuscripts & rare books",
                "sections": {
                    "090": "Manuscripts and rare books",
                    "091": "Manuscripts",
                    "092": "Block books",
                    "093": "Incunabula",
                    "094": "Printed books",
                    "095": "Books notable for bindings",
                    "096": "Books notable for illustrations",
                    "097": "Books notable for ownership",
                    "098": "Prohibited works, forgeries, hoaxes",
                    "099": "Books notable for format",
                },
            },
        },
    },
    "100": {
        "name": "Philosophy & Psychology",
        "full_breakdown": {
            "100-109": {
                "title": "Philosophy",
                "sections": {
                    "100": "Philosophy",
                    "101": "Theory of philosophy",
                    "102": "Miscellany of philosophy",
                    "103": "Dictionaries and encyclopedias",
                    "104": "Not assigned / reserved",
                    "105": "Serial publications",
                    "106": "Organizations and management",
                    "107": "Education, research, related topics",
                    "108": "Kinds of persons treatment",
                    "109": "Historical, geographic, persons treatment",
                },
            },
            "110-119": {
                "title": "Metaphysics",
                "sections": {
                    "110": "Metaphysics",
                    "111": "Ontology",
                    "112": "Not assigned / reserved",
                    "113": "Cosmology",
                    "114": "Space",
                    "115": "Time",
                    "116": "Change",
                    "117": "Structure",
                    "118": "Force and energy",
                    "119": "Number and quantity",
                },
            },
            "120-129": {
                "title": "Epistemology, causation, humankind",
                "sections": {
                    "120": "Epistemology, causation, humankind",
                    "121": "Epistemology (theory of knowledge)",
                    "122": "Causation",
                    "123": "Determinism and indeterminism",
                    "124": "Teleology",
                    "125": "Not assigned / reserved",
                    "126": "The self",
                    "127": "The unconscious and subconscious",
                    "128": "Humankind",
                    "129": "Origin and destiny of individual souls",
                },
            },
            "130-139": {
                "title": "Parapsychology and occultism",
                "sections": {
                    "130": "Parapsychology and occultism",
                    "131": "Parapsychological and occult methods",
                    "132": "Not assigned / reserved",
                    "133": "Specific topics in parapsychology and occultism",
                    "134": "Not assigned / reserved",
                    "135": "Dreams and mysteries",
                    "136": "Not assigned / reserved",
                    "137": "Divinatory graphology",
                    "138": "Physiognomy",
                    "139": "Phrenology",
                },
            },
            "140-149": {
                "title": "Specific philosophical schools",
                "sections": {
                    "140": "Specific philosophical schools",
                    "141": "Idealism and related systems",
                    "142": "Critical philosophy",
                    "143": "Intuitionism and Bergsonism",
                    "144": "Humanism and related systems",
                    "145": "Sensationalism",
                    "146": "Naturalism and related systems",
                    "147": "Pantheism and related systems",
                    "148": "Liberalism, eclecticism, traditionalism",
                    "149": "Other philosophical systems",
                },
            },
            "150-159": {
                "title": "Psychology",
                "sections": {
                    "150": "Psychology",
                    "151": "Not assigned / reserved",
                    "152": "Perception, movement, emotions, drives",
                    "153": "Mental processes and intelligence",
                    "154": "Subconscious and altered states",
                    "155": "Differential and developmental psychology",
                    "156": "Comparative psychology",
                    "157": "Not assigned / reserved",
                    "158": "Applied psychology",
                    "159": "Not assigned / reserved",
                },
            },
            "160-169": {
                "title": "Logic",
                "sections": {
                    "160": "Logic",
                    "161": "Induction",
                    "162": "Deduction",
                    "163": "Not assigned / reserved",
                    "164": "Not assigned / reserved",
                    "165": "Fallacies and sources of error",
                    "166": "Syllogisms",
                    "167": "Hypotheses",
                    "168": "Argument and persuasion",
                    "169": "Analogy",
                },
            },
            "170-179": {
                "title": "Ethics",
                "sections": {
                    "170": "Ethics",
                    "171": "Systems and doctrines",
                    "172": "Political ethics",
                    "173": "Ethics of family relationships",
                    "174": "Occupational ethics",
                    "175": "Ethics of recreation and leisure",
                    "176": "Sex and reproduction ethics",
                    "177": "Ethics of social relations",
                    "178": "Ethics of consumption",
                    "179": "Other ethical norms",
                },
            },
            "180-189": {
                "title": "Ancient, medieval, Eastern philosophy",
                "sections": {
                    "180": "Ancient, medieval, Eastern philosophy",
                    "181": "Eastern philosophy",
                    "182": "Pre-Socratic Greek philosophies",
                    "183": "Sophistic, Socratic, related philosophies",
                    "184": "Platonic philosophy",
                    "185": "Aristotelian philosophy",
                    "186": "Skeptic and Neoplatonic philosophies",
                    "187": "Epicurean philosophy",
                    "188": "Stoic philosophy",
                    "189": "Medieval Western philosophy",
                },
            },
            "190-199": {
                "title": "Modern Western philosophy",
                "sections": {
                    "190": "Modern Western philosophy",
                    "191": "Philosophy of the United States and Canada",
                    "192": "Philosophy of the British Isles",
                    "193": "Philosophy of Germany and Austria",
                    "194": "Philosophy of France",
                    "195": "Philosophy of Italy",
                    "196": "Philosophy of Spain and Portugal",
                    "197": "Philosophy of former Soviet Union",
                    "198": "Philosophy of Scandinavia",
                    "199": "Philosophy in other geographic areas",
                },
            },
        },
    },
    "200": {
        "name": "Religion",
        "full_breakdown": {
            "200-209": {
                "title": "Religion",
                "sections": {
                    "200": "Religion",
                    "201": "Philosophy and theory of religion",
                    "202": "Miscellany of religion",
                    "203": "Dictionaries and encyclopedias",
                    "204": "Special topics",
                    "205": "Serial publications",
                    "206": "Organizations and management",
                    "207": "Education, research, related topics",
                    "208": "Kinds of persons treatment",
                    "209": "Historical, geographic, persons treatment",
                },
            },
            "210-219": {
                "title": "Natural theology",
                "sections": {
                    "210": "Philosophy and theory of religion",
                    "211": "Concepts of God",
                    "212": "Existence, ways of knowing God",
                    "213": "Creation",
                    "214": "Theodicy",
                    "215": "Science and religion",
                    "216": "Not assigned / reserved",
                    "217": "Not assigned / reserved",
                    "218": "Humankind",
                    "219": "Not assigned / reserved",
                },
            },
            "220-229": {
                "title": "Bible",
                "sections": {
                    "220": "Bible",
                    "221": "Old Testament",
                    "222": "Historical books of Old Testament",
                    "223": "Poetic books of Old Testament",
                    "224": "Prophetic books of Old Testament",
                    "225": "New Testament",
                    "226": "Gospels and Acts",
                    "227": "Epistles",
                    "228": "Revelation (Apocalypse)",
                    "229": "Apocrypha and pseudepigrapha",
                },
            },
            "230-239": {
                "title": "Christian theology",
                "sections": {
                    "230": "Christianity and Christian theology",
                    "231": "God",
                    "232": "Jesus Christ and his family",
                    "233": "Humankind",
                    "234": "Salvation and grace",
                    "235": "Spiritual beings",
                    "236": "Eschatology",
                    "237": "Not assigned / reserved",
                    "238": "Creeds and catechisms",
                    "239": "Apologetics and polemics",
                },
            },
            "240-249": {
                "title": "Christian moral and devotional theology",
                "sections": {
                    "240": "Christian moral and devotional theology",
                    "241": "Moral theology",
                    "242": "Devotional literature",
                    "243": "Evangelistic writings",
                    "244": "Not assigned / reserved",
                    "245": "Texts of hymns",
                    "246": "Use of art in Christianity",
                    "247": "Church furnishings",
                    "248": "Christian experience, practice, life",
                    "249": "Christian observances in family life",
                },
            },
            "250-259": {
                "title": "Christian orders and local church",
                "sections": {
                    "250": "Christian orders and local church",
                    "251": "Preaching",
                    "252": "Texts of sermons",
                    "253": "Pastoral office and work",
                    "254": "Parish administration",
                    "255": "Religious congregations and orders",
                    "256": "Not assigned / reserved",
                    "257": "Not assigned / reserved",
                    "258": "Not assigned / reserved",
                    "259": "Pastoral care of specific families and groups",
                },
            },
            "260-269": {
                "title": "Christian social and ecclesiastical theology",
                "sections": {
                    "260": "Christian social and ecclesiastical theology",
                    "261": "Social theology and interreligious relations",
                    "262": "Ecclesiology",
                    "263": "Days, times, places of religious observance",
                    "264": "Public worship",
                    "265": "Sacraments, rites, other acts",
                    "266": "Missions",
                    "267": "Associations for religious work",
                    "268": "Religious education",
                    "269": "Spiritual renewal",
                },
            },
            "270-279": {
                "title": "History of Christianity",
                "sections": {
                    "270": "History of Christianity and Christian church",
                    "271": "Religious orders in church history",
                    "272": "Persecutions in church history",
                    "273": "Doctrinal controversies and heresies",
                    "274": "Christian church in Europe",
                    "275": "Christian church in Asia",
                    "276": "Christian church in Africa",
                    "277": "Christian church in North America",
                    "278": "Christian church in South America",
                    "279": "Christian church in other areas",
                },
            },
            "280-289": {
                "title": "Christian denominations",
                "sections": {
                    "280": "Christian denominations and sects",
                    "281": "Early church and Eastern churches",
                    "282": "Roman Catholic Church",
                    "283": "Anglican churches",
                    "284": "Protestant denominations of Continental origin",
                    "285": "Presbyterian, Reformed, Congregational",
                    "286": "Baptist, Disciples, Adventist",
                    "287": "Methodist and related churches",
                    "288": "Not assigned / reserved",
                    "289": "Other Christian denominations",
                },
            },
            "290-299": {
                "title": "Other religions",
                "sections": {
                    "290": "Other religions",
                    "291": "Comparative religion",
                    "292": "Classical (Greek and Roman) religion",
                    "293": "Germanic religion",
                    "294": "Religions of Indic origin",
                    "295": "Zoroastrianism",
                    "296": "Judaism",
                    "297": "Islam, Babism, Bahai Faith",
                    "298": "Not assigned / reserved",
                    "299": "Other religions",
                },
            },
        },
    },
    "300": {
        "name": "Social Sciences",
        "full_breakdown": {
            "300-309": {
                "title": "Social sciences",
                "sections": {
                    "300": "Social sciences",
                    "301": "Sociology & related sciences",
                    "302": "Social interaction",
                    "303": "Social processes",
                    "304": "Factors affecting social institutions",
                    "305": "Social groups",
                    "306": "Culture & institutions",
                    "307": "Communities",
                    "308": "Sociological research & statistics",
                    "309": "Historical, geographic, persons treatment",
                }
            },
            "310-319": {
                "title": "Statistics",
                "sections": {
                    "310": "Statistics",
                    "311": "Statistical methods",
                    "312": "Demography & related statistics",
                    "313": "Specific statistics",
                    "314-319": "Statistical data by area",
                }
            },
            "320-329": {
                "title": "Political science",
                "sections": {
                    "320": "Political science",
                    "321": "Systems of governments & states",
                    "322": "Relations of the state to organized groups",
                    "323": "Relations of the state to its residents",
                    "324": "Political elections & voting",
                    "325": "Politics of immigration & emigration",
                    "326": "Politics of slavery & emancipation",
                    "327": "International relations & politics",
                    "328": "The legislative & executive branches",
                    "329": "Political ideologies",
                }
            },
            "330-339": {
                "title": "Economics",
                "sections": {
                    "330": "Economics",
                    "331": "Labor & related topics",
                    "332": "Financial economics",
                    "333": "Land & related topics",
                    "334": "Cooperatives",
                    "335": "Socialism & related systems",
                    "336": "Public finance",
                    "337": "International economics",
                    "338": "Production",
                    "339": "Macroeconomics & related topics",
                }
            },
            "340-349": {
                "title": "Law",
                "sections": {
                    "340": "Law",
                    "341": "International law",
                    "342": "Constitutional & administrative law",
                    "343": "Military, labor & social law",
                    "344": "Social law & social welfare law",
                    "345": "Criminal law & criminology",
                    "346": "Private law",
                    "347": "Civil procedure & courts",
                    "348": "Laws, regulations, decrees of general utility",
                    "349": "Historical, geographic, persons treatment of law",
                }
            },
            "350-359": {
                "title": "Public administration & military science",
                "sections": {
                    "350": "Public administration",
                    "351": "Public administration & related topics",
                    "352": "General considerations of public administration",
                    "353": "Specific topics of public administration",
                    "354": "Administration of specific fields",
                    "355": "Military science & military history",
                    "356": "Military organization & personnel",
                    "357": "Specific aspects of military science",
                    "358": "Military science of nuclear/biological/chemical warfare",
                    "359": "Naval and maritime warfare",
                }
            },
            "360-369": {
                "title": "Social problems & social services",
                "sections": {
                    "360": "Social problems & social services",
                    "361": "Social welfare & social work",
                    "362": "Social welfare problems & services",
                    "363": "Environmental problems & services",
                    "364": "Criminology & penology",
                    "365": "Penal & related institutions",
                    "366": "Organizations & clubs",
                    "367": "Public welfare administration",
                    "368": "Insurance",
                    "369": "Welfare activities",
                }
            },
            "370-379": {
                "title": "Education",
                "sections": {
                    "370": "Education",
                    "371": "Schools & their activities; special topics",
                    "372": "Elementary education",
                    "373": "Secondary education",
                    "374": "Adult education",
                    "375": "Curricula",
                    "376": "Education of women",
                    "377": "Schools for specific groups",
                    "378": "Higher education",
                    "379": "Public policy issues in education",
                }
            },
            "380-389": {
                "title": "Commerce, communications & transportation",
                "sections": {
                    "380": "Commerce, communications & transportation",
                    "381": "Commerce & communications",
                    "382": "International commerce",
                    "383": "Postal service & related communications",
                    "384": "Telephone, radio & television",
                    "385": "Railroad transportation",
                    "386": "Inland waterway & ferry transportation",
                    "387": "Water & air transportation",
                    "388": "Motor land transportation",
                    "389": "Metrology & related topics",
                }
            },
            "390-399": {
                "title": "Customs, etiquette & folklore",
                "sections": {
                    "390": "Customs, etiquette & folklore",
                    "391": "Costume & personal appearance",
                    "392": "Customs of life cycle & domestic life",
                    "393": "Death customs",
                    "394": "General customs",
                    "395": "Etiquette",
                    "396": "Etiquette for women",
                    "397": "Etiquette for men",
                    "398": "Folklore",
                    "399": "Customs & folklore of specific groups",
                }
            },
        },
    },
    "400": {
        "name": "Language",
        "full_breakdown": {
            "400-409": {
                "title": "Language",
                "sections": {
                    "400": "Language",
                    "401": "Philosophy and theory",
                    "402": "Miscellany",
                    "403": "Dictionaries and encyclopedias",
                    "404": "Special topics",
                    "405": "Serial publications",
                    "406": "Organizations and management",
                    "407": "Education, research, related topics",
                    "408": "Kinds of persons treatment",
                    "409": "Historical, geographic, persons treatment",
                },
            },
            "410-419": {
                "title": "Linguistics",
                "sections": {
                    "410": "Linguistics",
                    "411": "Writing systems",
                    "412": "Etymology",
                    "413": "Dictionaries",
                    "414": "Phonology and phonetics",
                    "415": "Grammar",
                    "416": "Not assigned / reserved",
                    "417": "Dialectology and historical linguistics",
                    "418": "Standard usage and applied linguistics",
                    "419": "Sign languages",
                },
            },
            "420-429": {
                "title": "English & Old English",
                "sections": {
                    "420": "English and Old English",
                    "421": "English writing system and phonology",
                    "422": "English etymology",
                    "423": "English dictionaries",
                    "424": "Not assigned / reserved",
                    "425": "English grammar",
                    "426": "Not assigned / reserved",
                    "427": "English language variations",
                    "428": "Standard English usage",
                    "429": "Old English (Anglo-Saxon)",
                },
            },
            "430-439": {
                "title": "Germanic languages",
                "sections": {
                    "430": "Germanic languages",
                    "431": "German writing system and phonology",
                    "432": "German etymology",
                    "433": "German dictionaries",
                    "434": "Not assigned / reserved",
                    "435": "German grammar",
                    "436": "Not assigned / reserved",
                    "437": "German language variations",
                    "438": "Standard German usage",
                    "439": "Other Germanic languages",
                },
            },
            "440-449": {
                "title": "Romance languages",
                "sections": {
                    "440": "Romance languages",
                    "441": "French writing system and phonology",
                    "442": "French etymology",
                    "443": "French dictionaries",
                    "444": "Not assigned / reserved",
                    "445": "French grammar",
                    "446": "Not assigned / reserved",
                    "447": "French language variations",
                    "448": "Standard French usage",
                    "449": "Occitan, Catalan, related languages",
                },
            },
            "450-459": {
                "title": "Italian, Romanian, Rhaeto-Romanic",
                "sections": {
                    "450": "Italian, Romanian, Rhaeto-Romanic",
                    "451": "Italian writing system and phonology",
                    "452": "Italian etymology",
                    "453": "Italian dictionaries",
                    "454": "Not assigned / reserved",
                    "455": "Italian grammar",
                    "456": "Not assigned / reserved",
                    "457": "Italian language variations",
                    "458": "Standard Italian usage",
                    "459": "Romanian and Rhaeto-Romanic",
                },
            },
            "460-469": {
                "title": "Spanish & Portuguese",
                "sections": {
                    "460": "Spanish and Portuguese languages",
                    "461": "Spanish writing system and phonology",
                    "462": "Spanish etymology",
                    "463": "Spanish dictionaries",
                    "464": "Not assigned / reserved",
                    "465": "Spanish grammar",
                    "466": "Not assigned / reserved",
                    "467": "Spanish language variations",
                    "468": "Standard Spanish usage",
                    "469": "Portuguese",
                },
            },
            "470-479": {
                "title": "Latin & Italic",
                "sections": {
                    "470": "Latin and related Italic languages",
                    "471": "Classical Latin writing and phonology",
                    "472": "Classical Latin etymology",
                    "473": "Classical Latin dictionaries",
                    "474": "Not assigned / reserved",
                    "475": "Classical Latin grammar",
                    "476": "Not assigned / reserved",
                    "477": "Old, postclassical, Vulgar Latin",
                    "478": "Classical Latin usage",
                    "479": "Other Italic languages",
                },
            },
            "480-489": {
                "title": "Hellenic languages",
                "sections": {
                    "480": "Classical and modern Greek languages",
                    "481": "Classical Greek writing and phonology",
                    "482": "Classical Greek etymology",
                    "483": "Classical Greek dictionaries",
                    "484": "Not assigned / reserved",
                    "485": "Classical Greek grammar",
                    "486": "Not assigned / reserved",
                    "487": "Preclassical and postclassical Greek",
                    "488": "Classical Greek usage",
                    "489": "Modern Greek",
                },
            },
            "490-499": {
                "title": "Other languages",
                "sections": {
                    "490": "Other languages",
                    "491": "East Indo-European and Celtic languages",
                    "492": "Afro-Asiatic languages",
                    "493": "Non-Semitic Afro-Asiatic languages",
                    "494": "Altaic, Uralic, hyperborean languages",
                    "495": "East and Southeast Asian languages",
                    "496": "African languages",
                    "497": "North American native languages",
                    "498": "South American native languages",
                    "499": "Austronesian and other languages",
                },
            },
        },
    },
    "500": {
        "name": "Science & Mathematics",
        "full_breakdown": {
            "500-509": {
                "title": "Natural sciences & mathematics",
                "sections": {
                    "500": "Natural sciences & mathematics",
                    "501": "Philosophy & theory of science",
                    "502": "Miscellany of science",
                    "503": "Dictionaries, encyclopedias, concordances",
                    "504": "Natural history",
                    "505": "Serial publications of science",
                    "506": "Organizations & management of science",
                    "507": "Education, research, related topics",
                    "508": "Natural history by area",
                    "509": "Historical, geographic, persons treatment",
                },
            },
            "510-519": {
                "title": "Mathematics",
                "sections": {
                    "510": "Mathematics",
                    "511": "General principles of mathematics",
                    "512": "Algebra",
                    "513": "Arithmetic",
                    "514": "Topology",
                    "515": "Analysis",
                    "516": "Geometry",
                    "517": "Not assigned / reserved",
                    "518": "Numerical analysis",
                    "519": "Probabilities & applied mathematics",
                },
            },
            "520-529": {
                "title": "Astronomy & allied sciences",
                "sections": {
                    "520": "Astronomy & allied sciences",
                    "521": "Celestial mechanics",
                    "522": "Techniques, equipment, materials",
                    "523": "Specific celestial bodies & phenomena",
                    "524": "Not assigned / reserved",
                    "525": "Earth (astronomical geography)",
                    "526": "Mathematical geography",
                    "527": "Celestial navigation",
                    "528": "Ephemerides",
                    "529": "Chronology",
                },
            },
            "530-539": {
                "title": "Physics",
                "sections": {
                    "530": "Physics",
                    "531": "Classical mechanics",
                    "532": "Fluid mechanics",
                    "533": "Gas mechanics",
                    "534": "Sound & related vibrations",
                    "535": "Light & infrared/ultraviolet phenomena",
                    "536": "Heat",
                    "537": "Electricity & electronics",
                    "538": "Magnetism",
                    "539": "Modern physics",
                },
            },
            "540-549": {
                "title": "Chemistry",
                "sections": {
                    "540": "Chemistry",
                    "541": "Physical chemistry",
                    "542": "Techniques, equipment, materials",
                    "543": "Analytical chemistry",
                    "544": "Qualitative analysis",
                    "545": "Quantitative analysis",
                    "546": "Inorganic chemistry",
                    "547": "Organic chemistry",
                    "548": "Crystallography",
                    "549": "Mineralogy",
                },
            },
            "550-559": {
                "title": "Earth sciences & geology",
                "sections": {
                    "550": "Earth sciences",
                    "551": "Geology, hydrology, meteorology",
                    "552": "Petrology",
                    "553": "Economic geology",
                    "554": "Earth sciences of Europe",
                    "555": "Earth sciences of North America",
                    "556": "Earth sciences of Africa",
                    "557": "Earth sciences of Asia",
                    "558": "Earth sciences of Australasia & Pacific",
                    "559": "Earth sciences of other areas",
                },
            },
            "560-569": {
                "title": "Paleontology & fossil life",
                "sections": {
                    "560": "Paleontology & fossil life",
                    "561": "Paleobotany",
                    "562": "Fossil invertebrates",
                    "563": "Fossil protozoa & microscopic fossils",
                    "564": "Fossil mollusks & molluscoids",
                    "565": "Fossil arthropods",
                    "566": "Fossil chordates",
                    "567": "Fossil cold-blooded vertebrates",
                    "568": "Fossil birds",
                    "569": "Fossil mammals",
                },
            },
            "570-579": {
                "title": "Biology",
                "sections": {
                    "570": "Biology",
                    "571": "Physiology & related subjects",
                    "572": "Biochemistry",
                    "573": "Specific physiological systems in animals",
                    "574": "Not assigned / reserved",
                    "575": "Specific parts & systems in plants",
                    "576": "Genetics & evolution",
                    "577": "Ecology",
                    "578": "Natural history of organisms",
                    "579": "Microorganisms, fungi, algae",
                },
            },
            "580-589": {
                "title": "Plants (Botany)",
                "sections": {
                    "580": "Plants (Botany)",
                    "581": "Specific topics in natural history of plants",
                    "582": "Plants noted for specific characteristics",
                    "583": "Dicotyledons",
                    "584": "Monocotyledons",
                    "585": "Gymnosperms",
                    "586": "Seedless plants",
                    "587": "Vascular seedless plants",
                    "588": "Bryophytes",
                    "589": "Forest trees",
                },
            },
            "590-599": {
                "title": "Animals (Zoology)",
                "sections": {
                    "590": "Animals (Zoology)",
                    "591": "Specific topics in natural history of animals",
                    "592": "Invertebrates",
                    "593": "Marine & seashore invertebrates",
                    "594": "Mollusks & molluscoids",
                    "595": "Other invertebrates",
                    "596": "Vertebrates",
                    "597": "Cold-blooded vertebrates",
                    "598": "Birds",
                    "599": "Mammals",
                },
            },
        },
    },
    "600": {
        "name": "Technology (Applied Sciences)",
        "full_breakdown": {
            "600-609": {
                "title": "Technology & applied sciences",
                "sections": {
                    "600": "Technology (Applied sciences)",
                    "601": "Philosophy & theory of technology",
                    "602": "Miscellany of technology",
                    "603": "Dictionaries, encyclopedias, concordances",
                    "604": "Special topics of technology",
                    "605": "Serial publications of technology",
                    "606": "Organizations & management",
                    "607": "Education, research, related topics",
                    "608": "Inventions & patents",
                    "609": "Historical, geographic, persons treatment",
                },
            },
            "610-619": {
                "title": "Medicine & health",
                "sections": {
                    "610": "Medicine & health",
                    "611": "Human anatomy",
                    "612": "Human physiology",
                    "613": "Personal health & safety",
                    "614": "Incidence & prevention of disease",
                    "615": "Pharmacology & therapeutics",
                    "616": "Diseases",
                    "617": "Surgery & related medical specialties",
                    "618": "Gynecology, obstetrics, pediatrics, geriatrics",
                    "619": "Experimental medicine",
                },
            },
            "620-629": {
                "title": "Engineering",
                "sections": {
                    "620": "Engineering & allied operations",
                    "621": "Applied physics",
                    "622": "Mining & related operations",
                    "623": "Military & nautical engineering",
                    "624": "Civil engineering",
                    "625": "Engineering of railroads, roads",
                    "626": "Not assigned / reserved",
                    "627": "Hydraulic engineering",
                    "628": "Sanitary & municipal engineering",
                    "629": "Other branches of engineering",
                },
            },
            "630-639": {
                "title": "Agriculture",
                "sections": {
                    "630": "Agriculture & related technologies",
                    "631": "Techniques, equipment, materials",
                    "632": "Plant injuries, diseases, pests",
                    "633": "Field & plantation crops",
                    "634": "Orchards, fruits, forestry",
                    "635": "Garden crops (horticulture)",
                    "636": "Animal husbandry",
                    "637": "Processing dairy & related animal products",
                    "638": "Insect culture",
                    "639": "Hunting, fishing, conservation",
                },
            },
            "640-649": {
                "title": "Home & family management",
                "sections": {
                    "640": "Home economics & family living",
                    "641": "Food & drink",
                    "642": "Meals & table service",
                    "643": "Housing & household equipment",
                    "644": "Household utilities",
                    "645": "Household furnishings",
                    "646": "Sewing, clothing, personal living",
                    "647": "Management of public households",
                    "648": "Housekeeping",
                    "649": "Child rearing & home care",
                },
            },
            "650-659": {
                "title": "Management & auxiliary services",
                "sections": {
                    "650": "Management & auxiliary services",
                    "651": "Office services",
                    "652": "Processes of written communication",
                    "653": "Shorthand",
                    "654": "Not assigned / reserved",
                    "655": "Publishing",
                    "656": "Not assigned / reserved",
                    "657": "Accounting",
                    "658": "General management",
                    "659": "Advertising & public relations",
                },
            },
            "660-669": {
                "title": "Chemical & related technologies",
                "sections": {
                    "660": "Chemical engineering",
                    "661": "Industrial chemicals",
                    "662": "Explosives, fuels, related products",
                    "663": "Beverage technology",
                    "664": "Food technology",
                    "665": "Industrial oils, fats, waxes, gases",
                    "666": "Ceramic & allied technologies",
                    "667": "Cleaning, color, coating technologies",
                    "668": "Technology of other organic products",
                    "669": "Metallurgy",
                },
            },
            "670-679": {
                "title": "Manufacturing",
                "sections": {
                    "670": "Manufacturing",
                    "671": "Metalworking & primary metal products",
                    "672": "Iron, steel, other ferrous products",
                    "673": "Nonferrous metal products",
                    "674": "Lumber, wood, cork products",
                    "675": "Leather & fur processing",
                    "676": "Pulp & paper technology",
                    "677": "Textiles",
                    "678": "Elastomers & elastomer products",
                    "679": "Other products of specific materials",
                },
            },
            "680-689": {
                "title": "Manufacture for specific uses",
                "sections": {
                    "680": "Manufacture for specific uses",
                    "681": "Precision instruments & related devices",
                    "682": "Small forge work",
                    "683": "Hardware & household appliances",
                    "684": "Furnishings & home workshops",
                    "685": "Leather, fur goods, saddlery, shoes",
                    "686": "Printing & related activities",
                    "687": "Clothing & accessories",
                    "688": "Other final products & packaging",
                    "689": "Not assigned / reserved",
                },
            },
            "690-699": {
                "title": "Building & construction",
                "sections": {
                    "690": "Building & construction",
                    "691": "Building materials",
                    "692": "Auxiliary construction practices",
                    "693": "Specific materials & purposes",
                    "694": "Wood construction",
                    "695": "Roof covering",
                    "696": "Utilities (plumbing, heating, air)",
                    "697": "Heating, ventilating, air conditioning",
                    "698": "Finishing & fixtures",
                    "699": "Not assigned / reserved",
                },
            },
        },
    },
    "700": {
        "name": "Arts & Recreation",
        "full_breakdown": {
            "700-709": {
                "title": "Arts & recreation",
                "sections": {
                    "700": "Arts",
                    "701": "Philosophy & theory of fine and decorative arts",
                    "702": "Miscellany of fine and decorative arts",
                    "703": "Dictionaries, encyclopedias, concordances",
                    "704": "Special topics in fine and decorative arts",
                    "705": "Serial publications of fine and decorative arts",
                    "706": "Organizations & management",
                    "707": "Education, research, related topics",
                    "708": "Galleries, museums, private collections",
                    "709": "Historical, geographic, persons treatment",
                },
            },
            "710-719": {
                "title": "Civic & landscape design",
                "sections": {
                    "710": "Civic & landscape art",
                    "711": "Area planning (civic art)",
                    "712": "Landscape architecture",
                    "713": "Landscape architecture of trafficways",
                    "714": "Water features in landscape architecture",
                    "715": "Woody plants in landscape architecture",
                    "716": "Herbaceous plants in landscape architecture",
                    "717": "Structures in landscape architecture",
                    "718": "Landscape design of cemeteries",
                    "719": "Natural landscapes",
                },
            },
            "720-729": {
                "title": "Architecture",
                "sections": {
                    "720": "Architecture",
                    "721": "Architectural structure",
                    "722": "Architecture to ca. 300",
                    "723": "Architecture from ca. 300 to 1399",
                    "724": "Architecture from 1400",
                    "725": "Public structures",
                    "726": "Buildings for religious purposes",
                    "727": "Buildings for education and research",
                    "728": "Residential and related buildings",
                    "729": "Design and decoration of buildings",
                },
            },
            "730-739": {
                "title": "Sculpture, ceramics, metalwork",
                "sections": {
                    "730": "Sculpture and related arts",
                    "731": "Processes, forms, subjects of sculpture",
                    "732": "Sculpture to ca. 500",
                    "733": "Greek, Etruscan, Roman sculpture",
                    "734": "Sculpture from ca. 500 to 1399",
                    "735": "Sculpture from 1400",
                    "736": "Carving and carvings",
                    "737": "Numismatics and sigillography",
                    "738": "Ceramic arts",
                    "739": "Art metalwork",
                },
            },
            "740-749": {
                "title": "Graphic arts & decorative arts",
                "sections": {
                    "740": "Drawing and decorative arts",
                    "741": "Drawing and drawings",
                    "742": "Perspective in drawing",
                    "743": "Drawing and drawings by subject",
                    "744": "Not assigned / reserved",
                    "745": "Decorative arts",
                    "746": "Textile arts",
                    "747": "Interior decoration",
                    "748": "Glass",
                    "749": "Furniture and accessories",
                },
            },
            "750-759": {
                "title": "Painting",
                "sections": {
                    "750": "Painting",
                    "751": "Techniques, equipment, forms",
                    "752": "Color",
                    "753": "Symbolism, allegory, mythology, legend",
                    "754": "Genre paintings",
                    "755": "Religion in painting",
                    "756": "Not assigned / reserved",
                    "757": "Human figures in painting",
                    "758": "Nature and other subjects",
                    "759": "Historical, geographic, persons treatment",
                },
            },
            "760-769": {
                "title": "Graphic & related arts",
                "sections": {
                    "760": "Graphic arts; printmaking and prints",
                    "761": "Relief processes",
                    "762": "Not assigned / reserved",
                    "763": "Lithographic processes",
                    "764": "Chromolithography and serigraphy",
                    "765": "Metal engraving",
                    "766": "Mezzotinting, aquatinting, related processes",
                    "767": "Etching and drypoint",
                    "768": "Not assigned / reserved",
                    "769": "Prints",
                },
            },
            "770-779": {
                "title": "Photography & digital media",
                "sections": {
                    "770": "Photography, computer art, cinematography",
                    "771": "Techniques, equipment, materials",
                    "772": "Metallic salt processes",
                    "773": "Pigment processes",
                    "774": "Holography",
                    "775": "Digital photography",
                    "776": "Computer art (digital art)",
                    "777": "Cinematography and videography",
                    "778": "Specific fields of photography",
                    "779": "Photographs",
                },
            },
            "780-789": {
                "title": "Music",
                "sections": {
                    "780": "Music",
                    "781": "General principles and musical forms",
                    "782": "Vocal music",
                    "783": "Music for single voices",
                    "784": "Instruments and instrumental ensembles",
                    "785": "Ensembles with only one instrument per part",
                    "786": "Keyboard and other instruments",
                    "787": "Stringed instruments",
                    "788": "Wind instruments",
                    "789": "Not assigned / reserved",
                },
            },
            "790-799": {
                "title": "Sports, games & entertainment",
                "sections": {
                    "790": "Recreational and performing arts",
                    "791": "Public performances",
                    "792": "Stage presentations",
                    "793": "Indoor games and amusements",
                    "794": "Indoor games of skill",
                    "795": "Games of chance",
                    "796": "Athletic and outdoor sports and games",
                    "797": "Aquatic and air sports",
                    "798": "Equestrian sports and animal racing",
                    "799": "Fishing, hunting, shooting",
                },
            },
        },
    },
    "800": {
        "name": "Literature",
        "full_breakdown": {
            "800-809": {
                "title": "Literature and rhetoric",
                "sections": {
                    "800": "Literature and rhetoric",
                    "801": "Philosophy and theory",
                    "802": "Miscellany",
                    "803": "Dictionaries and encyclopedias",
                    "804": "Not assigned / reserved",
                    "805": "Serial publications",
                    "806": "Organizations and management",
                    "807": "Education, research, related topics",
                    "808": "Rhetoric and collections",
                    "809": "History, description, criticism",
                },
            },
            "810-819": {
                "title": "American literature in English",
                "sections": {
                    "810": "American literature in English",
                    "811": "American poetry in English",
                    "812": "American drama in English",
                    "813": "American fiction in English",
                    "814": "American essays in English",
                    "815": "American speeches in English",
                    "816": "American letters in English",
                    "817": "American humor and satire in English",
                    "818": "American miscellaneous writings in English",
                    "819": "Not assigned / reserved",
                },
            },
            "820-829": {
                "title": "English and Old English literatures",
                "sections": {
                    "820": "English and Old English literatures",
                    "821": "English poetry",
                    "822": "English drama",
                    "823": "English fiction",
                    "824": "English essays",
                    "825": "English speeches",
                    "826": "English letters",
                    "827": "English humor and satire",
                    "828": "English miscellaneous writings",
                    "829": "Old English (Anglo-Saxon) literature",
                },
            },
            "830-839": {
                "title": "German and related literatures",
                "sections": {
                    "830": "German and related literatures",
                    "831": "German poetry",
                    "832": "German drama",
                    "833": "German fiction",
                    "834": "German essays",
                    "835": "German speeches",
                    "836": "German letters",
                    "837": "German humor and satire",
                    "838": "German miscellaneous writings",
                    "839": "Other Germanic literatures",
                },
            },
            "840-849": {
                "title": "French and related literatures",
                "sections": {
                    "840": "French and related literatures",
                    "841": "French poetry",
                    "842": "French drama",
                    "843": "French fiction",
                    "844": "French essays",
                    "845": "French speeches",
                    "846": "French letters",
                    "847": "French humor and satire",
                    "848": "French miscellaneous writings",
                    "849": "Occitan, Catalan, related literatures",
                },
            },
            "850-859": {
                "title": "Italian, Romanian, related literatures",
                "sections": {
                    "850": "Italian, Romanian, related literatures",
                    "851": "Italian poetry",
                    "852": "Italian drama",
                    "853": "Italian fiction",
                    "854": "Italian essays",
                    "855": "Italian speeches",
                    "856": "Italian letters",
                    "857": "Italian humor and satire",
                    "858": "Italian miscellaneous writings",
                    "859": "Romanian and Rhaeto-Romanic literatures",
                },
            },
            "860-869": {
                "title": "Spanish and Portuguese literatures",
                "sections": {
                    "860": "Spanish and Portuguese literatures",
                    "861": "Spanish poetry",
                    "862": "Spanish drama",
                    "863": "Spanish fiction",
                    "864": "Spanish essays",
                    "865": "Spanish speeches",
                    "866": "Spanish letters",
                    "867": "Spanish humor and satire",
                    "868": "Spanish miscellaneous writings",
                    "869": "Portuguese literature",
                },
            },
            "870-879": {
                "title": "Latin and Italic literatures",
                "sections": {
                    "870": "Latin and Italic literatures",
                    "871": "Classical Latin poetry",
                    "872": "Classical Latin dramatic poetry",
                    "873": "Classical Latin epic fiction",
                    "874": "Classical Latin lyric poetry",
                    "875": "Classical Latin speeches",
                    "876": "Classical Latin letters",
                    "877": "Classical Latin satire and humor",
                    "878": "Classical Latin miscellaneous writings",
                    "879": "Other Italic literatures",
                },
            },
            "880-889": {
                "title": "Classical and modern Greek literatures",
                "sections": {
                    "880": "Classical and modern Greek literatures",
                    "881": "Classical Greek poetry",
                    "882": "Classical Greek dramatic poetry",
                    "883": "Classical Greek epic fiction",
                    "884": "Classical Greek lyric poetry",
                    "885": "Classical Greek speeches",
                    "886": "Classical Greek letters",
                    "887": "Classical Greek satire and humor",
                    "888": "Classical Greek miscellaneous writings",
                    "889": "Modern Greek literature",
                },
            },
            "890-899": {
                "title": "Other literatures",
                "sections": {
                    "890": "Other literatures",
                    "891": "East Indo-European and Celtic literatures",
                    "892": "Afro-Asiatic literatures",
                    "893": "Non-Semitic Afro-Asiatic literatures",
                    "894": "Altaic, Uralic, hyperborean literatures",
                    "895": "East and Southeast Asian literatures",
                    "896": "African literatures",
                    "897": "North American native literatures",
                    "898": "South American native literatures",
                    "899": "Austronesian and other literatures",
                },
            },
        },
    },
    "900": {
        "name": "History & Geography",
        "full_breakdown": {
            "900-909": {
                "title": "History & geography",
                "sections": {
                    "900": "History, geography, and auxiliary disciplines",
                    "901": "Philosophy and theory of history",
                    "902": "Miscellany of history",
                    "903": "Dictionaries, encyclopedias, concordances",
                    "904": "Collected accounts of events",
                    "905": "Serial publications of history",
                    "906": "Organizations and management",
                    "907": "Education, research, related topics",
                    "908": "History with respect to kinds of persons",
                    "909": "World history",
                },
            },
            "910-919": {
                "title": "Geography & travel",
                "sections": {
                    "910": "Geography and travel",
                    "911": "Historical geography",
                    "912": "Graphic representations of earth",
                    "913": "Geography of and travel in ancient world",
                    "914": "Geography of and travel in Europe",
                    "915": "Geography of and travel in Asia",
                    "916": "Geography of and travel in Africa",
                    "917": "Geography of and travel in North America",
                    "918": "Geography of and travel in South America",
                    "919": "Geography of and travel in Australasia, Pacific, polar regions",
                },
            },
            "920-929": {
                "title": "Biography & genealogy",
                "sections": {
                    "920": "Biography, genealogy, insignia",
                    "921": "Not assigned / reserved",
                    "922": "Not assigned / reserved",
                    "923": "Biography of people in social sciences",
                    "924": "Biography of people in arts",
                    "925": "Biography of people in science",
                    "926": "Biography of people in religion",
                    "927": "Biography of people in history",
                    "928": "Biography of women",
                    "929": "Genealogy, names, insignia",
                },
            },
            "930-939": {
                "title": "Ancient history",
                "sections": {
                    "930": "History of ancient world to ca. 499",
                    "931": "History of China to 420",
                    "932": "History of Egypt to 640",
                    "933": "History of Palestine to 70",
                    "934": "History of India to 647",
                    "935": "History of Mesopotamia and Iranian Plateau to 637",
                    "936": "History of Europe north and west of Italy to ca. 499",
                    "937": "History of Italy and adjacent territories to 476",
                    "938": "History of Greece to 323",
                    "939": "History of other parts of ancient world",
                },
            },
            "940-949": {
                "title": "History of Europe",
                "sections": {
                    "940": "History of Europe",
                    "941": "History of British Isles",
                    "942": "History of England and Wales",
                    "943": "History of Central Europe (Germany)",
                    "944": "History of France and Monaco",
                    "945": "History of Italy, San Marino, Vatican",
                    "946": "History of Iberian Peninsula and Andorra",
                    "947": "History of Eastern Europe (Russia)",
                    "948": "History of Scandinavia",
                    "949": "History of other parts of Europe",
                },
            },
            "950-959": {
                "title": "History of Asia",
                "sections": {
                    "950": "History of Asia",
                    "951": "History of China and adjacent areas",
                    "952": "History of Japan",
                    "953": "History of Arabian Peninsula and adjacent areas",
                    "954": "History of India and neighboring areas",
                    "955": "History of Iran",
                    "956": "History of Middle East",
                    "957": "History of Siberia (Asian Russia)",
                    "958": "History of Central Asia",
                    "959": "History of Southeast Asia",
                },
            },
            "960-969": {
                "title": "History of Africa",
                "sections": {
                    "960": "History of Africa",
                    "961": "History of Tunisia and Libya",
                    "962": "History of Egypt and Sudan",
                    "963": "History of Ethiopia and Eritrea",
                    "964": "History of Morocco and nearby islands",
                    "965": "History of Algeria",
                    "966": "History of West Africa and offshore islands",
                    "967": "History of Central Africa and offshore islands",
                    "968": "History of Southern Africa",
                    "969": "History of South Indian Ocean islands",
                },
            },
            "970-979": {
                "title": "History of North America",
                "sections": {
                    "970": "History of North America",
                    "971": "History of Canada",
                    "972": "History of Mexico, Central America, West Indies",
                    "973": "History of United States",
                    "974": "History of Northeastern United States",
                    "975": "History of Southeastern United States",
                    "976": "History of South Central United States",
                    "977": "History of North Central United States",
                    "978": "History of Western United States",
                    "979": "History of Great Basin and Pacific Slope",
                },
            },
            "980-989": {
                "title": "History of South America",
                "sections": {
                    "980": "History of South America",
                    "981": "History of Brazil",
                    "982": "History of Argentina",
                    "983": "History of Chile",
                    "984": "History of Bolivia",
                    "985": "History of Peru",
                    "986": "History of Colombia and Ecuador",
                    "987": "History of Venezuela",
                    "988": "History of Guyana",
                    "989": "History of Paraguay and Uruguay",
                },
            },
            "990-999": {
                "title": "History of other areas",
                "sections": {
                    "990": "History of other areas",
                    "991": "Not assigned / reserved",
                    "992": "Not assigned / reserved",
                    "993": "History of New Zealand",
                    "994": "History of Australia",
                    "995": "History of Melanesia and nearby islands",
                    "996": "History of other parts of Pacific",
                    "997": "History of Atlantic Ocean islands",
                    "998": "History of Arctic islands and Antarctica",
                    "999": "History of extraterrestrial worlds (speculative)",
                },
            },
        },
    },
}


def get_main_classes() -> dict:
    """Return all 10 main Dewey classes with descriptions."""
    return {
        class_id: data["name"]
        for class_id, data in DEWEY_TAXONOMY.items()
    }


def get_divisions(class_id: str) -> dict:
    """Return all divisions for a specific class (e.g., '300' returns all 300-level divisions)."""
    if class_id not in DEWEY_TAXONOMY:
        return {}
    return DEWEY_TAXONOMY[class_id]["divisions"]


def get_detailed_breakdown(class_id: str) -> dict | None:
    """Return detailed section breakdown for all 10 main Dewey classes (000-900)."""
    return DEWEY_DETAILED.get(class_id)


def search_taxonomy(query: str) -> list[dict]:
    """Search Dewey taxonomy by keyword across all classes and divisions."""
    results = []
    query_lower = query.lower()

    for class_id, class_data in DEWEY_TAXONOMY.items():
        # Search class name
        if query_lower in class_data["name"].lower():
            results.append({
                "type": "class",
                "dewey_number": class_id,
                "name": class_data["name"],
                "match": "class_name",
            })

        # Search divisions
        for div_range, div_name in class_data["divisions"].items():
            if query_lower in div_name.lower():
                results.append({
                    "type": "division",
                    "dewey_number": div_range,
                    "name": div_name,
                    "match": "division_name",
                })

    return results


if __name__ == "__main__":
    # Quick reference printout
    print("=== DEWEY DECIMAL CLASSIFICATION ===\n")
    for class_id in sorted(DEWEY_TAXONOMY.keys()):
        class_data = DEWEY_TAXONOMY[class_id]
        print(f"{class_id}: {class_data['name']}")
        for div_range, div_name in class_data["divisions"].items():
            print(f"  {div_range}: {div_name}")
        print()
